<a href="https://colab.research.google.com/github/Aksaiful007/Skill-Morph/blob/main/Assignment_3_NumPy_and_Pandas_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
Student Performance Dataset Analysis
Dataset Information
Student Performance Dataset (StudentsPerformance.csv)

1000 students with academic performance data
8 columns: gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score
Score Range: 0-100 for each subject
Demographics: Male/Female, 5 ethnic groups, 6 education levels, standard/free lunch, test prep completed/none
"""

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [17]:
#Task 1.1: Data Loading and Exploration
import numpy as np
import pandas as pd

# Load the dataset
df = pd.read_csv('StudentsPerformance.csv')

# Your tasks:
# 1. Display first 10 rows
# 2. Show dataset shape and info()
# 3. Display unique values in each categorical column
# 4. Show basic statistics for all score columns

# Your code here:
#1. Display first 10 rows
print(df[:10])
print()
#2. Show dataset shape and info()
print(df.shape)
print()
print(df.info())
#3. Display unique values in each categorical column
columns = df.select_dtypes(include=['object']).columns
for i in columns:
    unique_values = df[i].unique()
    print(f"{i}: {unique_values}")
#4show basic statistics for all score columns
print()
print(df.describe())

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard
5  female        group B          associate's degree      standard
6  female        group B                some college      standard
7    male        group B                some college  free/reduced
8    male        group D                 high school  free/reduced
9  female        group B                 high school  free/reduced

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75
5                    none          71             83             78
6               completed          88             95             92
7                    none          40             43             39
8               completed          64             64             67
9                    none          38             60             50

(1000, 8)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
None
gender: ['female' 'male']
race/ethnicity: ['group B' 'group C' 'group A' 'group D' 'group E']
parental level of education: ["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']
lunch: ['standard' 'free/reduced']
test preparation course: ['none' 'completed']

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [15]:
#Task 1.2: NumPy Array Operations
# Convert score columns to numpy arrays
mscores = df['math score'].values
rscores = df['reading score'].values
wscores = df['writing score'].values

# Your tasks:
# 1. Calculate mean, median, std, min, max for each subject using NumPy
# 2. Find total students who scored above 80 in math
# 3. Find total students who scored below 50 in any subject
# 4. Calculate the overall average score across all three subjects

# Expected output example:
# Math - Mean: 66.1, Median: 66.0, Std: 15.2
# Students with math > 80: 132
# Students with any score < 50: 178

# Your code here:
#1. Calculate mean, median, std, min, max for each subject using NumPy
subjects = {'Math': mscores, 'Reading': rscores, 'Writing': wscores}
for subject, scores in subjects.items():
    mean = np.mean(scores)
    median = np.median(scores)
    std = np.std(scores)
    min_score = np.min(scores)
    max_score = np.max(scores)
    print(f"{subject} - Mean: {mean:.1f}, Median: {median:.1f}, Std: {std:.1f}, Min: {min_score}, Max: {max_score}")
#2. Find total students who scored above 80 in math
m80plus = np.sum(mscores > 80)
print()
print(f"Students with math > 80: {m80plus}")
#3. Find total students who scored below 50 in any subject
below50 = np.sum((mscores < 50) | (rscores < 50) | (wscores < 50))
print()
print(f"Students with any score < 50: {below50}")

Math - Mean: 66.1, Median: 66.0, Std: 15.2, Min: 0, Max: 100
Reading - Mean: 69.2, Median: 70.0, Std: 14.6, Min: 17, Max: 100
Writing - Mean: 68.1, Median: 69.0, Std: 15.2, Min: 10, Max: 100

Students with math > 80: 176

Students with any score < 50: 188

In [16]:
# Task 2.1: Identify and Handle Missing Data
# Check the dataset for any missing values
# Your tasks:
# 1. Check for null values in each column using .isnull().sum()
# 2. Check for any impossible values (scores > 100 or < 0)
# 3. Display summary of data quality

# Note: This dataset is clean, but let's verify!

# Your code here:
#1. Check for null values in each column using .isnull().sum()
mscores = df['math score'].values
rscores = df['reading score'].values
wscores = df['writing score'].values
print(df.isnull().sum())
print()
#2. Check for any impossible values (scores > 100 or < 0)
invalid_math = np.sum((mscores < 0) | (mscores > 100))
invalid_reading = np.sum((rscores < 0) | (rscores > 100))
invalid_writing = np.sum((wscores < 0) | (wscores > 100))
print(f"Invalid Math Scores: {invalid_math}")
print(f"Invalid Reading Scores: {invalid_reading}")
print(f"Invalid Writing Scores: {invalid_writing}")
print()
#3. Display summary of data quality
print(df.info())

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

Invalid Math Scores: 0
Invalid Reading Scores: 0
Invalid Writing Scores: 0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
None

In [12]:
#Task 2.2: Create and Fix Missing Value
# Artificially create missing data for practice
import numpy as np
import pandas as pd

# Your tasks:
# 1. Make a copy of the dataset: df_practice = df.copy()
# 2. Randomly set 50 math scores to np.nan
# 3. Randomly set 30 writing scores to np.nan
# 4. Fill missing math scores with the MEDIAN math score
# 5. Fill missing writing scores with the MEAN writing score
# 6. Verify no missing values remain

# Steps to follow:
# Step 1: Create copy and show original missing values
df = pd.read_csv('StudentsPerformance.csv')
df_practice = df.copy()
print("Original missing values:", df_practice.isnull().sum())
mscores = df['math score'].values
rscores = df['reading score'].values
wscores = df['writing score'].values

# Step 2: Create missing data
np.random.seed(42)  # For reproducible results
missing_math_idx = np.random.choice(df_practice.index, 50)
#step 3
missing_writing_idx = np.random.choice(df_practice.index, 30)
print(missing_math_idx)
print(missing_writing_idx)

# Continue the task...
# Your code here:
#4. Fill missing math scores with the median math score:
df_practice["math score"] = df_practice["math score"].replace(df_practice["math score"].median(), np.nan)
print(df_practice["math score"])
#5 Filling missing writing score with mean writing score:
df_practice["writing score"] = df_practice["writing score"].replace(df_practice["writing score"].mean(), np.nan)
print(df_practice["writing score"])

Original missing values: gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64
[102 435 860 270 106  71 700  20 614 121 466 214 330 458  87 372  99 871
 663 130 661 308 769 343 491 413 805 385 191 955 276 160 459 313  21 252
 747 856 560 474  58 510 681 475 699 975 782 189 957 686]
[957 562 875 566 243 831 504 130 484 818 646  20 840 166 273 387 600 315
  13 241 776 345 564 897 339  91 366 955 454 427]
0      72.0
1      69.0
2      90.0
3      47.0
4      76.0
       ...
995    88.0
996    62.0
997    59.0
998    68.0
999    77.0
Name: math score, Length: 1000, dtype: float64
0      74
1      88
2      93
3      44
4      75
       ..
995    95
996    55
997    65
998    77
999    86
Name: writing score, Length: 1000, dtype: int64

In [13]:
#Task 3.1:Answer Simple Questions About Student Performance
# Your tasks:
# 1. Display first 5 rows using .head()
# 2. Display last 5 rows using .tail()
# 3. Show dataset shape using .shape
# 4. Show column names using .columns
# 5. Show data types using .dtypes
# 6. Show basic info using .info()

# Your code here:
import numpy as np
import pandas as pd
df = pd.read_csv('StudentsPerformance.csv')
#1. Display first 5 rows using .head()
print(df.head())
print()
#2. Display last 5 rows using .tail()
print(df.tail())
print()
#3. Show dataset shape using .shape
print(df.shape)
print()
#4. Show column names using .columns
print(df.columns)
print()
#5. Show data types using .dtypes
print(df.dtypes)
print()
#6. Show basic info using .info()
print(df.info())

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75

     gender race/ethnicity parental level of education         lunch  \
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

(1000, 8)

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
None

In [ ]:
#Task 3.2: Basic Groupby Analysis
# Comprehensive groupby analysis
# Your tasks:
import numpy as np
import pandas as pd
df = pd.read_csv('StudentsPerformance.csv')
# 1. Group by 'gender' and calculate:
#    - Average scores in all subjects
#    - Count of students

# 2. Group by 'test preparation course' and show:
#    - Mean scores for each subject
#    - Show which subject benefits most from test prep

# 3. Group by 'parental level of education' and calculate:
#    - Average math score for each education level
#    - Rank education levels by math performance

# 4. Group by 'lunch' type and show:
#    - Average scores for each subject
#    - Count of students in each lunch category

# Your code here:
#1. Group by 'gender' and calculate average, count of students
grouped = df.groupby('gender')[['math score', 'reading score', 'writing score']].agg(['mean', 'count'])
print("grouped by gender: \n", grouped)
print()
#2. Group by 'test preparation course' and show mean scores
pres_grouped = df.groupby('test preparation course')[['math score', 'reading score', 'writing score']].mean()
print("grouped by test preparation course: \n", pres_grouped)
print()
#3. Group by 'parental level of education' and calculate average math score
par_grouped = df.groupby('parental level of education')['math score'].mean().sort_values()
print("grouped by parental level of education :\n", par_grouped)
print()#4. Group by 'lunch' type and show average scores, count of students
lunch_grouped = df.groupby('lunch')[['math score', 'reading score', 'writing score']].agg(['mean', 'count'])
print("grouped by lunch:\n", lunch_grouped)

grouped by gender:
        math score       reading score       writing score
             mean count          mean count          mean count
gender
female  63.633205   518     72.608108   518     72.467181   518
male    68.728216   482     65.473029   482     63.311203   482

grouped by test preparation course:
                          math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673

grouped by parental level of education :
 parental level of education
high school           62.137755
some high school      63.497207
some college          67.128319
associate's degree    67.882883
bachelor's degree     69.389831
master's degree       69.745763
Name: math score, dtype: float64

grouped by lunch:
              math score       reading score       writing score
                   mean count          mean count          mean count
lunch
free/reduced  58.921127   355     64.653521   355     63.022535   355
standard      70.034109   645     71.654264   645     70.823256   645

In [ ]:
#Task 3.3: Use your data analysis skills to answer these easy questions:

# 1. Who performs better in math - males or females?
#    - Calculate average math score by gender
#    - Show the difference between male and female average

# 2. Which subject do students perform best in overall?
#    - Calculate the overall average for math, reading, and writing
#    - Rank the subjects from highest to lowest average score

# 3. What's the impact of parental education?
#    - Find the average total score for each parental education level
#    - Identify which education level leads to highest student performance
import numpy as np
import pandas as pd
df = pd.read_csv('StudentsPerformance.csv')
# 1. Who performs better in math male or female?
gpgender = df.groupby('gender')['math score'].mean()
print("Average math score of :", gpgender)
print("difference between male math score and female math score average:", round((abs(gpgender['male'] - gpgender['female'])), 2))
print()
if gpgender['male'] > gpgender['female']:
    print("Males perform better in math")
else:
    print("Females perform better in math")
print()
# 2. Which subject do students perform best in overall?
overall_avg = df[['math score', 'reading score', 'writing score']].mean().sort_values()
print("Overall average scores:\n", overall_avg)
print("Students perform best in:", overall_avg.idxmax(), "-", overall_avg.max())
print()
print("students perform medium in:", overall_avg.index[1], "-", overall_avg.iloc[1])
print()
print("students perform worst in:", overall_avg.idxmin(), "-", overall_avg.min())
print()
# 3. What's the impact of parental education?
avgbypredu = df.groupby('parental level of education')[['math score', 'reading score', 'writing score']].mean()
# Calculate total score by summing the mean scores for each subject
avgbypredu['total score'] = avgbypredu[['math score', 'reading score', 'writing score']].sum(axis=1)
print("Average total score by parental education level:\n", avgbypredu['total score'])
highest_edu = avgbypredu['total score'].idxmax()
print("Highest student performance is from parental education level:  ", highest_edu, "-", avgbypredu['total score'].max())
print()
lowest_edu = avgbypredu['total score'].idxmin()
print("The lowest student performance is from parental education level:  ", lowest_edu, "-", avgbypredu['total score'].min())
print()

Average math score of : gender
female    63.633205
male      68.728216
Name: math score, dtype: float64
difference between male math score and female math score average: 5.1

Males perform better in math

Overall average scores:
 math score       66.089
writing score    68.054
reading score    69.169
dtype: float64
Students perform best in: reading score - 69.169

students perform medium in: writing score - 68.054

students perform worst in: math score - 66.089

Average total score by parental education level:
 parental level of education
associate's degree    208.707207
bachelor's degree     215.771186
high school           189.290816
master's degree       220.796610
some college          205.429204
some high school      195.324022
Name: total score, dtype: float64
Highest student performance is from parental education level:   master's degree - 220.79661016949152

The lowest student performance is from parental education level:   high school - 189.2908163265306

In [ ]:
# Print first 10 rows of DataFrame using iloc
import numpy as np
import pandas as pd
df = pd.read_csv('StudentsPerformance.csv')
print(df.iloc[:10])

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard
5  female        group B          associate's degree      standard
6  female        group B                some college      standard
7    male        group B                some college  free/reduced
8    male        group D                 high school  free/reduced
9  female        group B                 high school  free/reduced

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75
5                    none          71             83             78
6               completed          88             95             92
7                    none          40             43             39
8               completed          64             64             67
9                    none          38             60             50